// Reads SUPABASE_URL and SUPABASE_ANON_KEY from environment variables
// and writes them into build/js/config.js — generated fresh on every build,
// never committed to git.

const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.join(__dirname, '..', '.env') });
dotenv.config({ path: path.join(__dirname, '..', '.env.local'), override: true });

const rawSupabaseUrl = process.env.SUPABASE_URL || '';
const SUPABASE_URL = rawSupabaseUrl.replace(/\/rest\/v1\/?$/, '').replace(/\/$/, '');
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn(
    '\n⚠️  SUPABASE_URL or SUPABASE_ANON_KEY is not set.\n' +
    '   Set them in .env.local (for local dev) or in your Vercel project settings (for deploys).\n'
  );
}

const output = `// AUTO-GENERATED by scripts/generate-config.js — do not edit directly, do not commit real values.
window.__SUPABASE_CONFIG__ = {
  url: "${SUPABASE_URL}",
  anonKey: "${SUPABASE_ANON_KEY}"
};
`;

const outPath = path.join(__dirname, '..', 'build', 'js', 'config.js');
fs.writeFileSync(outPath, output);
console.log('✔ Generated build/js/config.js');
